# Python 3.9 environment loading
FROM python:3.9

# System dependencies
RUN apt-get update && apt-get install -y libfftw3-dev gfortran bash gedit xauth

# Working directory 
WORKDIR /app

# Copy source code
COPY . .

# Install necessary dependencies
RUN pip install --no-cache-dir numpy jupyter matplotlib scipy

# Installation
RUN python setup.py install

# Command to run Jupyter Notebook
CMD ["bash"]
